###
# Welcome to the new js2coffee 2.0, now
# rewritten to use the esprima parser.
# try it out!
###
Template.course_questions.onCreated ->
myQuestions = [
  {
    question: 'What is 10/2?'
    answers:
      a: '3'
      b: '5'
      c: '115'
    correctAnswer: 'b'
  }
  {
    question: 'What is 30/3?'
    answers:
      a: '3'
      b: '5'
      c: '10'
    correctAnswer: 'c'
  }
]
quizContainer = document.getElementById('quiz')
resultsContainer = document.getElementById('results')
submitButton = document.getElementById('submit')

generateQuiz = (questions, quizContainer, resultsContainer, submitButton) ->
  # show questions right away

  showQuestions = (questions, quizContainer) ->
    # we'll need a place to store the output and the answer choices
    output = []
    answers = undefined
    # for each question...
    i = 0
    while i < questions.length
      # first reset the list of answers
      answers = []
      # for each available answer...
      for letter of questions[i].answers
        `letter = letter`
        # ...add an html radio button
        answers.push '<label>' + '<input type="radio" name="question' + i + '" value="' + letter + '">' + letter + ': ' + questions[i].answers[letter] + '</label>'
      # add this question and its answers to the output
      output.push '<div class="question">' + questions[i].question + '</div>' + '<div class="answers">' + answers.join('') + '</div>'
      i++
    # finally combine our output list into one string of html and put it on the page
    quizContainer.innerHTML = output.join('')
    return

  showResults = (questions, quizContainer, resultsContainer) ->
    # gather answer containers from our quiz
    answerContainers = quizContainer.querySelectorAll('.answers')
    # keep track of user's answers
    userAnswer = ''
    numCorrect = 0
    # for each question...
    i = 0
    while i < questions.length
      # find selected answer
      userAnswer = (answerContainers[i].querySelector('input[name=question' + i + ']:checked') or {}).value
      # if answer is correct
      if userAnswer == questions[i].correctAnswer
        # add to the number of correct answers
        numCorrect++
        # color the answers green
        answerContainers[i].style.color = 'lightgreen'
      else
        # color the answers red
        answerContainers[i].style.color = 'red'
      i++
    # show number of correct answers out of total
    resultsContainer.innerHTML = numCorrect + ' out of ' + questions.length
    return

  showQuestions questions, quizContainer
  # on submit, show results

  submitButton.onclick = ->
    showResults questions, quizContainer, resultsContainer
    return

  return

generateQuiz myQuestions, quizContainer, resultsContainer, submitButton

# ---
# generated by js2coffee 2.2.0